package com.yizhaoqi.smartpai.model;

/** Agent 结束或暂停的机器可读原因。 */
public enum AgentTerminalReason {
    ANSWERED,
    PARTIAL_EVIDENCE,
    INSUFFICIENT_EVIDENCE,
    CONFLICTED_EVIDENCE,
    WAITING_CLARIFICATION,
    WAITING_APPROVAL,
    DUPLICATE_ACTION_LIMIT,
    NO_PROGRESS,
    ROUND_BUDGET_EXHAUSTED,
    TOOL_BUDGET_EXHAUSTED,
    TOKEN_BUDGET_EXHAUSTED,
    TIME_BUDGET_EXHAUSTED,
    USER_CANCELLED,
    RETRYABLE_FAILURE,
    FATAL_FAILURE
}
